_target_: src.modules.imagenet_module.ImageNetModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-3
  weight_decay: 1e-4

main_scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    _partial_: true
    T_max: null # Requires knowing total number of training steps
    eta_min: 0

warmup_steps: 1e4

warmup_scheduler:
    _target_: torch.optim.lr_scheduler.LinearLR
    _partial_: true
    start_factor: 1e-2
    total_iters: ${module.warmup_steps}

# ViT-S/16
net:
  _target_: torchvision.models.vision_transformer._vision_transformer
  patch_size: 16
  num_layers: 12
  num_heads: 6
  hidden_dim: 384
  mlp_dim: 1536
  weights: null
  progress: False

# compile model for faster training with pytorch 2.0
compile: ???